### ISSUE TITLE
/ in group name breaks summary

### ISSUE THREAD

**Issue by databus23** [dgodd/concourse-summary#12]
We have groups named something like `stable/mitaka`.

This leads to whole page not rendering with this console error:
```
[Error] Error: Syntax error, unrecognized expression: .custom-images/mitaka
	error (jquery.min.js:2:13525)
	select (jquery.min.js:2:22351)
	find (jquery.min.js:2:24963)
	init (jquery.min.js:2:25453)
	r (jquery.min.js:2:615)
	(anonymous function) (refresh.js:19)
	forEach
	(anonymous function) (refresh.js:6)
	each (jquery.min.js:2:2820)
	scaletext (refresh.js:3)
	Global Code (refresh.js:57)
```

**Comment by dgodd** [comment]
Is your pipeline public? If so can you give me a link to investigate?

**Comment by dgodd** [comment]
@databus23 I believe that I have now fixed this issue. Concourse Summary no longer uses jquery and has a simpler plan for making text fit. If you could please confirm that this now works for you then we can close this issue
