### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by benmoss** [dgodd/concourse-summary#14]
Hey Dave,

We're trying to add our Concourse and getting an error.

https://concourse-summary-crystal.cfapps.io/host/ci.pcf-gemfire.com?login_form

![screen shot 2016-12-15 at 4 52 00 pm](https://cloud.githubusercontent.com/assets/239754/21243456/f5188fe4-c2e6-11e6-8fe0-ce8634ca4e19.png)

**Comment by dgodd** [comment]
I turned on `SKIP_SSL_VALIDATION` for concourse-summary-crystal.cfapps.io ; I think with username and password supplied it will work

**Comment by benmoss** [comment]
Rad, it works now! Thanks @dgodd!
