### ISSUE TITLE
collapse groups / show groups blows away ?login_form

### ISSUE THREAD

**Issue by benmoss** [dgodd/concourse-summary#15]
since you handled my other bug report so well:

when you use the "Show Groups" / "Collapse Groups" links, they don't keep the `login_form` query param around in the URL, so the page doesn't work anymore. Figured out I could do `?login_form&ignore_groups` and it works, but would be nice if the links worked :).

**Comment by dgodd** [comment]
All params are now kept

**Comment by benmoss** [comment]
wooooooooooohooooooooooooooooooooo
