### ISSUE TITLE
Upgraded to 2.7.0, private pipelines are missing

### ISSUE THREAD

**Issue by ryankilroy** [dgodd/concourse-summary#20]
We have a chrome box machine we use for monitoring our concourse. We login using basic auth and have not modified anything other than upgrading concourse from 2.6.0 to 2.7.0.

On Concourse Summary, we can only see one pipeline visible (our public pipeline), even when we login using `?login_form`

Our pipelines look like this (`/api/v1/pipelines/`):
```
[
 {
 name: "VisiblePublicPipeline",
 url: "/teams/main/pipelines/VisiblePublicPipeline",
 paused: false,
 public: true,
 team_name: "main"
 },
 {
 name: "ThisPipelineUsedToBeVisible",
 url: "/teams/main/pipelines/ThisPipelineUsedToBeVisible",
 paused: false,
 public: false,
 team_name: "main"
 },
 {
 name: "ThisPipelineUsedToBeVisibleToo",
 url: "/teams/main/pipelines/ThisPipelineUsedToBeVisibleToo",
 paused: false,
 public: false,
 team_name: "main"
 },
...
]
```

**Comment by dgodd** [comment]
@ryanmattcollins It turns out concourse no longer allows setting both basic auth and cookie auth (and also crystal and concourse disagree about header escaping)

I believe it is now fixed, could you check for you, and give me an example login somewhere if it doesn't? (a fake team would be perfect)

**Comment by ryankilroy** [comment]
Looks good, thanks @dgodd!
