### ISSUE TITLE
Add an indication of when the pipeline last ran

### ISSUE THREAD

**Issue by kdykeman** [dgodd/concourse-summary#25]
I was recently "fooled" into thinking things were OK by a green box when in fact one of the resource checks had been failing (orange) for 30+ days. Some indication of the last time the pipeline ran to completion would have helped me notice that things were broken.

**Comment by dgodd** [comment]
I'm not sure how to determine "ran to completion" with concourse. I could show the most recent time anything ran, but I'm not sure that would help? The other option I can think of would be to show an orange border if any resources are failing/orange.

**Comment by kdykeman** [comment]
An orange border sounds like the simplest thing and would probably most quickly draw attention.

**Comment by dgodd** [comment]
@kdykeman ConcourseSummary should now show an orange border if any input resources have broken checks. Please tell me if this solves your problem

**Comment by kdykeman** [comment]
Perfect, thanks!

**Comment by kdykeman** [comment]
Just wanted to give you props on this change... It's been a massive help!

**Comment by dgodd** [comment]
Awesome, thanks
