### ISSUE TITLE
Concourse Login Issues

### ISSUE THREAD

**Issue by geofffranks** [dgodd/concourse-summary#27]
I'm trying to integrate concourse-summary with a concourse that has pipelines which are not publicly available. I tried adding the `?login_form` param to the end of the URL for the concourse, in the `HOSTS` env var on the app. This triggers concourse-summary to pop up an authentication form, but when I put in the username/password, I still don't see any pipeline data.

TCP dumping on my concourse node shows no evidence of an Auth header, or the `/api/v1/teams/#{team_name}/auth/token` call occurring. Any ideas what i'm doing wrong?

**Comment by geofffranks** [comment]
Looks like there might be some caching involved that prevented me from seeing the auth request. I caught another tcp dump of it in there. However, the ATC-Authorization cookie being set isn't being passed back to concourse for the pipeline retrieval calls (Concourse version 3.3.2)

**Comment by dgodd** [comment]
At the moment concourse summary auth with username/password, is that what you are using, or are you using github auth (or other)?

I personally only use a publicly accessible concourse server so I don't notice if APIs for auth change.

**Comment by geofffranks** [comment]
We have both github + basic auth set up on this concourse. I was attempting to use basic auth for concourse-summary

**Comment by dgodd** [comment]
OK. Thanks for the confirmation, I'll try and work this out

**Comment by dgodd** [comment]
Hi @geofffranks I just checked against buildpacks.ci.cf-app.com which is on concourse 3.3.4 and used http://concourse-summary-crystal.cfapps.io/host/buildpacks.ci.cf-app.com?ignore_groups&login_form and my basic auth to concourse username/password auth worked. Are you still having a problem?

**Comment by geofffranks** [comment]
It's still not working for us - same version of Concourse. I tried disabling the github auth on concourse, so it was *only* basic auth, no luck. Tried removing the extra site (it was configured for two), still no luck. Tried changing the concourse password in case it didn't like it for some reason, and also no joy. I've tried against fresh pushes of the app, restarts, as well as new browser sessions + cleanrooms across safari, chrome, and firefox.

In all cases, once concourse-summary has my credentials, it shows me no pipelines, as if  i were logged out.

**Comment by dgodd** [comment]
Are you using https://concourse-summary-crystal.cfapps.io/ or your own instance of concourse summary? If you are using your own, would you mind trying to use https://concourse-summary-crystal.cfapps.io/ and see if it has the same problems?

**Comment by geofffranks** [comment]
I'm seeing the same problem when going through that copy as well.

**Comment by dgodd** [comment]
Are you able to give me access to your concourse deploy through some direct channel (eg. dave@goddard.id.au)

**Comment by geofffranks** [comment]
probably not. we'll just use it with the publicly viewable pipelines instead
