### ISSUE TITLE
License

### ISSUE THREAD

**Issue by srbry** [dgodd/concourse-summary#29]
Hi,

I have created a golang port of this code and would like to share it back with the opensource community. Maintaining it as a fork seems slightly crazy, however as this repo has no license I cannot share the code in any other way.

Happy to share the golang version of this code in whatever way you would like.

**Comment by dgodd** [comment]
@srby I have added an MIT license.

Out of interest why a golang port? Was there a problem you had? or was it a fun conversion?

**Comment by sambryant4** [comment]
@dgodd thanks.

A bit of both. It was fun to convert it but I also had issues with builds every time crystal releases a new version. The breaking changes in patch versions of the programming language became annoying.

We had hard coded out CI to use a specific crystal version but then when you fix concourse summary to work with the latest version we can't take your changes. It was basically becoming more effort than we wanted to maintain an up to date version. We also have no developers with any crystal experience so it was also quite confusing for us if we needed to debug anything.
