### ISSUE TITLE
Sometimes the box isn't 100% filled in

### ISSUE THREAD

**Issue by idoru** [dgodd/concourse-summary#30]
Depending on the number of passing/failing jobs for a given pipeline, sometimes their percentage widths don't add up to 100%, leaving part of the box unshaded even when there are no jobs that haven't been execute yet.

Example:
![buildbox](https://user-images.githubusercontent.com/237596/33673710-9181144e-da7b-11e7-85b6-cb1f4981fe2e.png)

Corresponding inline styles in DOM:
![concourse-summary-css](https://user-images.githubusercontent.com/237596/33673636-5571d01a-da7b-11e7-9a27-176087dee139.png)

**Comment by dgodd** [comment]
Thanks @idoru, I have changed the code to use `ceiling` instead of `floor` when determining the percentage widths
