### ISSUE TITLE
Completely green pipelines should be GIFs

### ISSUE THREAD

**Issue by idoru** [dgodd/concourse-summary#31]
As a software engineer who uses concourse summary to view a summary of their CI
When a pipeline has no failing tasks
I want to see a GIF in its place which has a celebratory tone
Because it would make me feel even happier than green boxes since they can be a bit boring after a while.

**Comment by dgodd** [comment]
@idoru I have set the pipeline to show items from giphy if the giphy param has a noun. The images have a green overlay. Please suggest any changes.

[Example with cats](http://concourse-summary-crystal.cfapps.io/host/buildpacks.ci.cf-app.com?ignore_groups&giphy=cat)

**Comment by idoru** [comment]
So good! This is the best Concourse dashboard ever!
