### ISSUE TITLE
Toggling "ignore_groups" on breaks when giphy is on

### ISSUE THREAD

**Issue by idoru** [dgodd/concourse-summary#32]
Steps to reproduce:

1. Go to an excellent dashboard with some giphy action, like https://concourse-summary-crystal.cfapps.io/host/buildpacks.ci.cf-app.com?giphy=funny+cat
2. Click on the "ignore groups" button next to the octocat in the upper right
3. App unexpectedly 500's with mangled URI in address bar: https://concourse-summary-crystal.cfapps.io/host/buildpacks.ci.cf-app.com?giphy&ignore_groups

**Comment by dgodd** [comment]
@idoru This should be fixed by https://github.com/dgodd/concourse-summary/commit/6fab627cc927f26cedb4df7b2a64935a8855e9e7
